config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "restaurants#index"

  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  validates :name, length: {minimum: 3}, uniqueness: true

  has_many :reviews, dependent: :destroy
  belongs_to :user
  has_attached_file :image,
                    :styles => { :medium => "300x300", :thumb => "100x100"},
                    :default_url =>"/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def was_created_by?(user)
    user.id === self.user_id
  end

  def build_review(params, user)
    review = reviews.new(restaurant_id: self.id, thoughts: params[:thoughts],
                          rating: params[:rating])
    review.user_id = user.id
    return review
  end

  def average_rating
    return 'N/A' if reviews.count < 1
    reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }

  belongs_to :restaurant
  belongs_to :user
  has_many :endorsements
  validates :rating, inclusion: (1..5)
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :reviews
  has_many :restaurants

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
    @current_user = current_user
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_user.id
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :image)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to restaurants_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.build_review(review_params, current_user)
    if @review.save
      redirect_to restaurants_path
    elsif @review.errors[:user]
      redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
    else
      render 'new'
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    flash[:notice] = 'Your review was deleted succesfully'
    redirect_to restaurants_path
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to_new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    '★' * rating.to_i + '☆' * (5 - rating.to_i)
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title YelpClone
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta(charset="UTF-8")

  %body
    %header
      = link_to "Add a restaurant", new_restaurant_path, class: "btn btn-primary"
      - if user_signed_in?
        = link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-default"
      - else
        = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-default"
        = link_to "Log in", new_user_session_path, class: "btn btn-default"
        = link_to "Sign up", new_user_registration_path, class: "btn btn-default"
      - if notice
        .alert.alert-success= notice
      - elsif alert
        .alert.alert-danger= alert
    = yield
    %footer

app/views/restaurants/_form.html.haml
=form_for @restaurant, html: {multipart: true} do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_field :description
  = f.file_field :image
  = f.submit

app/views/restaurants/edit.html.haml
%h1 Edit
= render 'form'

app/views/restaurants/index.html.haml
%h1 Where do you wanna eat next?
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    %h4= link_to restaurant.name, restaurant_path(restaurant)
    = image_tag restaurant.image.url(:thumb)
    %strong= "Average rating: #{star_rating(restaurant.average_rating)}"
    - if @current_user && restaurant.was_created_by?(@current_user)
      = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant), class: "btn btn-link"
      = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete, class: "btn btn-link"
    - unless @current_user && @current_user.has_reviewed?(restaurant)
      = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant), class: "btn btn-link"
    - restaurant.reviews.each do |review|
      %p= review.thoughts
      %strong= "Rating: #{review.rating}"
      %p= "Reviewed #{time_ago_in_words(review.created_at)} ago"
      = link_to "Endorse review", review_endorsements_path(review), method: :post, class: 'endorsements-link'
      %span.endorsements-count= review.endorsements.count
      = "endorsement".pluralize review.endorsements.count
      - if @current_user && @current_user.has_reviewed?(restaurant)
        = link_to "Delete review", review_path(review), method: :delete, class: "btn btn-link"
- else
  %h4 No restaurants yet!

app/views/restaurants/new.html.haml
%section#errors
  %ul
  - @restaurant.errors.full_messages.each do |message|
    %li=message
=render 'form'

app/views/restaurants/show.html.haml
%h1= @restaurant.name
= image_tag @restaurant.image.url(:medium)
%p= @restaurant.description

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave review'